.forgejo/workflows: Do not upload artifact on missing secrets
Forgejo does not give access to the repository secrets to forked
repositories, which means it is not possible to upload artifacts.
As a workaround, skip the complete step.

diff --git a/.forgejo/workflows/build-deb.yml b/.forgejo/workflows/build-deb.yml
--- a/.forgejo/workflows/build-deb.yml
+++ b/.forgejo/workflows/build-deb.yml
@@ -33,7 +33,13 @@ jobs:
         run: cpack -G DEB
         working-directory: /src/build
       - name: Upload Debian package
-        run: upload-artifact -d ${{ matrix.image }} *.deb
+        run: |
+          if [ $USERNAME ]
+          then
+            upload-artifact -d ${{ matrix.image }} *.deb
+          else
+            echo "Skipping due to missing secrets" >&2
+          fi
         working-directory: /src/build
         env:
           URL: ${{ vars.STORE_URL }}
diff --git a/.forgejo/workflows/build-w64-mingw32.yml b/.forgejo/workflows/build-w64-mingw32.yml
--- a/.forgejo/workflows/build-w64-mingw32.yml
+++ b/.forgejo/workflows/build-w64-mingw32.yml
@@ -31,7 +31,13 @@ jobs:
         run: cpack -G NSIS
         working-directory: src/build
       - name: Upload installer
-        run: upload-artifact *.exe
+        run: |
+          if [ $USERNAME ]
+          then
+            upload-artifact *.exe
+          else
+            echo "Skipping due to missing secrets" >&2
+          fi
         working-directory: src/build
         env:
           URL: ${{ vars.STORE_URL }}
